package am.platform.movie.api.rest.response;

/**
 * @author mher13.02.94@gmail.com
 */

public enum ResponseMessage {

    EMAIL_IS_NOT_VALID,
    EMAIL_ALREADY_EXISTS,
    PASSWORD_IS_INVALID,
    PASSWORDS_DO_NOT_MATCH,
    USER_DOES_NOT_EXIST,
    ACCOUNT_WAS_CREATED,
    ACCOUNT_DELETED,
    ACCOUNT_VERIFIED,
    CONFIRMATION_CODE_SENT,
    USER_NOT_FOUND,
    CODE_DOES_NOT_MATCH,
    PASSWORDS_DOES_NOT_MATCH,
    CODE_EXPIRED,
    REGISTER_USER_ALREADY_EXISTS,
    ACCOUNT_DOES_NOT_VERIFIED_CONFIRMATION_CODE_SENT,
    CURRENT_AND_NEW_PASSWORDS_ARE_MATCHING,
    PARENT_CATEGORY_NOT_FOUND,
    CATEGORY_NOT_FOUND,
    CONFIRMATION_CODE_EVENT_IS_NULL
}
